
services:
  db:
    image: mariadb:11
    container_name: symfony-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanban_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony-backend
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app_network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: vue-frontend
  #   ports:
  #     - "5173:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
