nelmio_api_doc:
  documentation:
    info:
      title: 'Kanban API'
      description: 'API REST sécurisée pour gérer les utilisateurs, listes et cartes d’un Kanban.'
      version: 1.0.0
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []
  areas:
    path_patterns:
      - ^/api(?!/doc$) # Toutes les routes sous /api sauf /api/doc
