nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:5173']  # ton frontend en dev
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/api/': ~
